# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glf < Formula
  desc "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
  homepage "https://github.com/igusev/glf"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/igusev/glf/releases/download/v0.6.1/glf-0.6.1-darwin_amd64.tar.gz"
      sha256 "591d07e64e12d7e6457e7904d1c1a322bff78d4634a5bcdcbeb2c7ad0f4a872e"

      define_method(:install) do
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/igusev/glf/releases/download/v0.6.1/glf-0.6.1-darwin_arm64.tar.gz"
      sha256 "34fac79203aca5a77bec222ec46e2ded1d58fab4583550f259325304b24383d3"

      define_method(:install) do
        bin.install "glf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.6.1/glf-0.6.1-linux_amd64.tar.gz"
      sha256 "a7ae05da01ed7221fc9d90b67976deb5bae3995bdb790cb453b66c092d212606"
      define_method(:install) do
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.6.1/glf-0.6.1-linux_armv6.tar.gz"
      sha256 "3a3d5f567a699e07a0367ac7e7f7960d0ed85138505ed38a0f1c1601478cb2f9"
      define_method(:install) do
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.6.1/glf-0.6.1-linux_arm64.tar.gz"
      sha256 "cc013cf6d5fa960c6ca7f930e40bf9792cd517be1b29781ae7b6e79c0c1e9e51"
      define_method(:install) do
        bin.install "glf"
      end
    end
  end

  test do
    system "#{bin}/glf", "--help"
  end
end
