# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glf < Formula
  desc "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
  homepage "https://github.com/igusev/glf"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/igusev/glf/releases/download/v0.2.5/glf-0.2.5-darwin_amd64.tar.gz"
      sha256 "46afbcc2df5bdc65714c946745f67f3499f62be48fdc3b3ab47ee20b35d50fde"

      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/igusev/glf/releases/download/v0.2.5/glf-0.2.5-darwin_arm64.tar.gz"
      sha256 "58765c326f7620622fad9dc6c6d94e0769523d7c7b788f11db51be720b496764"

      def install
        bin.install "glf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.2.5/glf-0.2.5-linux_amd64.tar.gz"
      sha256 "04a3b990c0c36bfaf27d5b09217bd553c3c95b46f0e147e21fb11612ee97d0d9"
      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.2.5/glf-0.2.5-linux_armv6.tar.gz"
      sha256 "8b7271a6fb4440698ce324e87a0f06657c6d2aa8bf4a0961252909634575d8b5"
      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.2.5/glf-0.2.5-linux_arm64.tar.gz"
      sha256 "bce38b606e642fd6abf17c5133c13ce1957bcec6767242f33bb76154712c5151"
      def install
        bin.install "glf"
      end
    end
  end

  test do
    system "#{bin}/glf", "--help"
  end
end
