# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glf < Formula
  desc "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
  homepage "https://github.com/igusev/glf"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/igusev/glf/releases/download/v0.3.4/glf-0.3.4-darwin_amd64.tar.gz"
      sha256 "82e97752e8684e27a33dc6fa1573ba070a635f4dd06abd01166f97dbc355ea63"

      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/igusev/glf/releases/download/v0.3.4/glf-0.3.4-darwin_arm64.tar.gz"
      sha256 "92074edc005f9735ad1e28dff93dec11b1f0814f60dcaa448338c298b8b93c33"

      def install
        bin.install "glf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.3.4/glf-0.3.4-linux_amd64.tar.gz"
      sha256 "ecd29f9ec2460ed51eba1c9430df800caedda43f77aab9b0adddf76929dcce1a"
      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.3.4/glf-0.3.4-linux_armv6.tar.gz"
      sha256 "79c946b0f3b6d558654c96b9dfea3383de0e3a4b2ab5ed9b7129118fd020fc6a"
      def install
        bin.install "glf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/igusev/glf/releases/download/v0.3.4/glf-0.3.4-linux_arm64.tar.gz"
      sha256 "10596314c75ea83622940d42b884624f909b9a1ef36385dfe446a65c4dd89e27"
      def install
        bin.install "glf"
      end
    end
  end

  test do
    system "#{bin}/glf", "--help"
  end
end
